/**
 * Infogalactic
 * Infogalactic news API
 *
 * OpenAPI spec version: 0.0.0
 * Contact: activedecay@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Infogalactic);
  }
}(this, function(expect, Infogalactic) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Infogalactic.NewsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewsApi', function() {
    describe('createNews', function() {
      it('should call createNews successfully', function(done) {
        //uncomment below and update the code to test createNews
        //instance.createNews(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createWithArray', function() {
      it('should call createWithArray successfully', function(done) {
        //uncomment below and update the code to test createWithArray
        //instance.createWithArray(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNews', function() {
      it('should call deleteNews successfully', function(done) {
        //uncomment below and update the code to test deleteNews
        //instance.deleteNews(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readNews', function() {
      it('should call readNews successfully', function(done) {
        //uncomment below and update the code to test readNews
        //instance.readNews(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readNewsById', function() {
      it('should call readNewsById successfully', function(done) {
        //uncomment below and update the code to test readNewsById
        //instance.readNewsById(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateNews', function() {
      it('should call updateNews successfully', function(done) {
        //uncomment below and update the code to test updateNews
        //instance.updateNews(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadNewsImage', function() {
      it('should call uploadNewsImage successfully', function(done) {
        //uncomment below and update the code to test uploadNewsImage
        //instance.uploadNewsImage(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
