/**
 * Infogalactic
 * Infogalactic news API
 *
 * OpenAPI spec version: 0.0.0
 * Contact: activedecay@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/News'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/News'));
  } else {
    // Browser globals (root is window)
    if (!root.Infogalactic) {
      root.Infogalactic = {};
    }
    root.Infogalactic.StageApi = factory(root.Infogalactic.ApiClient, root.Infogalactic.News);
  }
}(this, function(ApiClient, News) {
  'use strict';

  /**
   * Stage service.
   * @module api/StageApi
   * @version 0.0.0
   */

  /**
   * Constructs a new StageApi. 
   * @alias module:api/StageApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the pushHistoryNode operation.
     * @callback module:api/StageApi~pushHistoryNodeCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Place a new node in the history with the contents of the current stage
     * @param {module:api/StageApi~pushHistoryNodeCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.pushHistoryNode = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['news_auth'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = null;

      return this.apiClient.callApi(
        '/stage/save', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readStage operation.
     * @callback module:api/StageApi~readStageCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/News>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns news items in the stage
     * Production quality phase check before finalizing release; inspect staged changes before committing to history.
     * @param {module:api/StageApi~readStageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/News>}
     */
    this.readStage = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['news_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [News];

      return this.apiClient.callApi(
        '/stage', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
